#!/bin/bash
# ==============================================================================
# Script: update-pnpm
# Beschrijving: Updatet pnpm via corepack.
# ==============================================================================

corepack use pnpm@latest && pnpm -v
